[2022-08-26 19:02:16,370] {processor.py:163} INFO - Started process (PID=16991) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:02:16,370] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:02:16,370] {logging_mixin.py:109} INFO - [2022-08-26 19:02:16,370] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:02:16,576] {logging_mixin.py:109} INFO - [2022-08-26 19:02:16,575] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:02:16,589] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:02:16,592] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.223 seconds
[2022-08-26 19:02:50,276] {processor.py:163} INFO - Started process (PID=17001) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:02:50,276] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:02:50,277] {logging_mixin.py:109} INFO - [2022-08-26 19:02:50,277] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:02:50,462] {logging_mixin.py:109} INFO - [2022-08-26 19:02:50,461] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:02:50,474] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:02:50,476] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.201 seconds
[2022-08-26 19:04:44,542] {processor.py:163} INFO - Started process (PID=17004) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:04:44,543] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:04:44,543] {logging_mixin.py:109} INFO - [2022-08-26 19:04:44,543] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:04:44,751] {logging_mixin.py:109} INFO - [2022-08-26 19:04:44,751] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:04:44,764] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:04:44,767] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.225 seconds
[2022-08-26 19:06:14,677] {processor.py:163} INFO - Started process (PID=17011) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:06:14,677] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:06:14,678] {logging_mixin.py:109} INFO - [2022-08-26 19:06:14,677] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:06:14,853] {logging_mixin.py:109} INFO - [2022-08-26 19:06:14,852] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:06:14,865] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:06:14,868] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.192 seconds
[2022-08-26 19:08:23,028] {processor.py:163} INFO - Started process (PID=17021) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:08:23,028] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:08:23,029] {logging_mixin.py:109} INFO - [2022-08-26 19:08:23,029] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:08:23,207] {logging_mixin.py:109} INFO - [2022-08-26 19:08:23,207] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:08:23,219] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:08:23,222] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.195 seconds
[2022-08-26 19:09:45,820] {processor.py:163} INFO - Started process (PID=17025) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:09:45,820] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:09:45,820] {logging_mixin.py:109} INFO - [2022-08-26 19:09:45,820] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:09:45,998] {logging_mixin.py:109} INFO - [2022-08-26 19:09:45,998] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:09:46,010] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:09:46,013] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.194 seconds
[2022-08-26 19:11:23,562] {processor.py:163} INFO - Started process (PID=17030) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:11:23,562] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:11:23,562] {logging_mixin.py:109} INFO - [2022-08-26 19:11:23,562] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:11:23,773] {logging_mixin.py:109} INFO - [2022-08-26 19:11:23,772] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:11:23,786] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:11:23,789] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.228 seconds
[2022-08-26 19:12:28,969] {processor.py:163} INFO - Started process (PID=17037) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:12:28,969] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:12:28,970] {logging_mixin.py:109} INFO - [2022-08-26 19:12:28,970] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:12:29,147] {logging_mixin.py:109} INFO - [2022-08-26 19:12:29,146] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:12:29,159] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:12:29,162] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.193 seconds
[2022-08-26 19:14:54,962] {processor.py:163} INFO - Started process (PID=17043) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:14:54,962] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:14:54,963] {logging_mixin.py:109} INFO - [2022-08-26 19:14:54,963] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:14:55,164] {logging_mixin.py:109} INFO - [2022-08-26 19:14:55,164] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:14:55,178] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:14:55,181] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.219 seconds
[2022-08-26 19:22:39,201] {processor.py:163} INFO - Started process (PID=17048) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:22:39,201] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:22:39,201] {logging_mixin.py:109} INFO - [2022-08-26 19:22:39,201] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:22:39,416] {logging_mixin.py:109} INFO - [2022-08-26 19:22:39,415] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:22:39,430] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:22:39,432] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.232 seconds
[2022-08-26 19:23:10,346] {processor.py:163} INFO - Started process (PID=17064) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:23:10,347] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:23:10,347] {logging_mixin.py:109} INFO - [2022-08-26 19:23:10,347] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:23:10,522] {logging_mixin.py:109} INFO - [2022-08-26 19:23:10,521] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:23:10,533] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:23:10,536] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.190 seconds
[2022-08-26 19:26:12,290] {processor.py:163} INFO - Started process (PID=17071) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:26:12,291] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:26:12,291] {logging_mixin.py:109} INFO - [2022-08-26 19:26:12,291] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:26:12,495] {logging_mixin.py:109} INFO - [2022-08-26 19:26:12,495] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:26:12,508] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:26:12,511] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.221 seconds
[2022-08-26 19:26:51,134] {processor.py:163} INFO - Started process (PID=17078) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:26:51,134] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:26:51,134] {logging_mixin.py:109} INFO - [2022-08-26 19:26:51,134] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:26:51,309] {logging_mixin.py:109} INFO - [2022-08-26 19:26:51,308] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:26:51,321] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:26:51,324] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.190 seconds
[2022-08-26 19:28:23,748] {processor.py:163} INFO - Started process (PID=17084) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:28:23,748] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:28:23,748] {logging_mixin.py:109} INFO - [2022-08-26 19:28:23,748] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:28:23,955] {logging_mixin.py:109} INFO - [2022-08-26 19:28:23,955] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:28:23,968] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:28:23,971] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.224 seconds
[2022-08-26 19:31:40,972] {processor.py:163} INFO - Started process (PID=17091) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:31:40,972] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:31:40,972] {logging_mixin.py:109} INFO - [2022-08-26 19:31:40,972] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:31:41,170] {logging_mixin.py:109} INFO - [2022-08-26 19:31:41,170] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:31:41,183] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:31:41,186] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.215 seconds
[2022-08-26 19:33:13,396] {processor.py:163} INFO - Started process (PID=17099) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:33:13,396] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:33:13,396] {logging_mixin.py:109} INFO - [2022-08-26 19:33:13,396] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:33:13,571] {logging_mixin.py:109} INFO - [2022-08-26 19:33:13,571] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:33:13,583] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:33:13,586] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.190 seconds
[2022-08-26 19:33:47,920] {processor.py:163} INFO - Started process (PID=17104) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:33:47,937] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:33:47,938] {logging_mixin.py:109} INFO - [2022-08-26 19:33:47,938] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:33:48,139] {logging_mixin.py:109} INFO - [2022-08-26 19:33:48,139] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:33:48,152] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:33:48,156] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.237 seconds
[2022-08-26 19:35:56,253] {processor.py:163} INFO - Started process (PID=17114) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:35:56,253] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:35:56,253] {logging_mixin.py:109} INFO - [2022-08-26 19:35:56,253] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:35:56,469] {logging_mixin.py:109} INFO - [2022-08-26 19:35:56,468] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:35:56,482] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:35:56,485] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.233 seconds
[2022-08-26 19:40:59,023] {processor.py:163} INFO - Started process (PID=17120) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:40:59,023] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:40:59,023] {logging_mixin.py:109} INFO - [2022-08-26 19:40:59,023] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:40:59,225] {logging_mixin.py:109} INFO - [2022-08-26 19:40:59,225] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:40:59,238] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:40:59,241] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.219 seconds
[2022-08-26 19:55:28,429] {processor.py:163} INFO - Started process (PID=17129) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:55:28,429] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 19:55:28,429] {logging_mixin.py:109} INFO - [2022-08-26 19:55:28,429] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:55:28,673] {logging_mixin.py:109} INFO - [2022-08-26 19:55:28,673] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 19:55:28,686] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 19:55:28,688] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.260 seconds
[2022-08-26 20:01:56,470] {processor.py:163} INFO - Started process (PID=17142) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:01:56,471] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 20:01:56,471] {logging_mixin.py:109} INFO - [2022-08-26 20:01:56,471] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:01:56,681] {logging_mixin.py:109} INFO - [2022-08-26 20:01:56,680] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 20:01:56,695] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:01:56,698] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.228 seconds
[2022-08-26 20:10:33,654] {processor.py:163} INFO - Started process (PID=17153) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:10:33,654] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 20:10:33,654] {logging_mixin.py:109} INFO - [2022-08-26 20:10:33,654] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:10:33,861] {logging_mixin.py:109} INFO - [2022-08-26 20:10:33,860] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 20:10:33,875] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:10:33,879] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.226 seconds
[2022-08-26 20:14:19,585] {processor.py:163} INFO - Started process (PID=17162) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:14:19,586] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 20:14:19,586] {logging_mixin.py:109} INFO - [2022-08-26 20:14:19,586] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:14:19,794] {logging_mixin.py:109} INFO - [2022-08-26 20:14:19,794] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 20:14:19,807] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:14:19,811] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.226 seconds
[2022-08-26 20:21:28,471] {processor.py:163} INFO - Started process (PID=17170) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:21:28,471] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 20:21:28,471] {logging_mixin.py:109} INFO - [2022-08-26 20:21:28,471] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:21:28,672] {logging_mixin.py:109} INFO - [2022-08-26 20:21:28,671] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 20:21:28,685] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:21:28,688] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.218 seconds
[2022-08-26 20:22:00,015] {processor.py:163} INFO - Started process (PID=17182) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:22:00,016] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 20:22:00,016] {logging_mixin.py:109} INFO - [2022-08-26 20:22:00,016] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:22:00,188] {logging_mixin.py:109} INFO - [2022-08-26 20:22:00,187] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 20:22:00,200] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:22:00,202] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.187 seconds
[2022-08-26 20:28:18,795] {processor.py:163} INFO - Started process (PID=17186) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:28:18,795] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 20:28:18,795] {logging_mixin.py:109} INFO - [2022-08-26 20:28:18,795] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:28:19,001] {logging_mixin.py:109} INFO - [2022-08-26 20:28:19,001] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 20:28:19,015] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:28:19,019] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.225 seconds
[2022-08-26 20:28:50,566] {processor.py:163} INFO - Started process (PID=17206) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:28:50,566] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 20:28:50,566] {logging_mixin.py:109} INFO - [2022-08-26 20:28:50,566] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:28:50,750] {logging_mixin.py:109} INFO - [2022-08-26 20:28:50,750] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 20:28:50,762] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:28:50,765] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.200 seconds
[2022-08-26 20:29:22,482] {processor.py:163} INFO - Started process (PID=17209) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:29:22,483] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 20:29:22,483] {logging_mixin.py:109} INFO - [2022-08-26 20:29:22,483] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:29:22,655] {logging_mixin.py:109} INFO - [2022-08-26 20:29:22,654] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 20:29:22,666] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:29:22,669] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.187 seconds
[2022-08-26 20:29:53,842] {processor.py:163} INFO - Started process (PID=17217) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:29:53,843] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 20:29:53,843] {logging_mixin.py:109} INFO - [2022-08-26 20:29:53,843] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:29:54,018] {logging_mixin.py:109} INFO - [2022-08-26 20:29:54,018] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 20:29:54,030] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:29:54,033] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.191 seconds
[2022-08-26 20:36:52,237] {processor.py:163} INFO - Started process (PID=17225) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:36:52,237] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 20:36:52,237] {logging_mixin.py:109} INFO - [2022-08-26 20:36:52,237] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:36:52,425] {logging_mixin.py:109} INFO - [2022-08-26 20:36:52,424] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 20:36:52,437] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:36:52,440] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.203 seconds
[2022-08-26 20:53:00,604] {processor.py:163} INFO - Started process (PID=17230) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:53:00,604] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 20:53:00,605] {logging_mixin.py:109} INFO - [2022-08-26 20:53:00,605] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:53:00,996] {logging_mixin.py:109} INFO - [2022-08-26 20:53:00,995] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 20:53:01,010] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:53:01,013] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.409 seconds
[2022-08-26 20:53:31,983] {processor.py:163} INFO - Started process (PID=17247) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:53:31,983] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 20:53:31,983] {logging_mixin.py:109} INFO - [2022-08-26 20:53:31,983] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:53:32,160] {logging_mixin.py:109} INFO - [2022-08-26 20:53:32,160] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 20:53:32,172] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:53:32,175] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.193 seconds
[2022-08-26 20:54:03,107] {processor.py:163} INFO - Started process (PID=17252) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:54:03,107] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 20:54:03,107] {logging_mixin.py:109} INFO - [2022-08-26 20:54:03,107] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:54:03,285] {logging_mixin.py:109} INFO - [2022-08-26 20:54:03,284] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 20:54:03,297] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:54:03,300] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.194 seconds
[2022-08-26 20:54:34,262] {processor.py:163} INFO - Started process (PID=17264) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:54:34,263] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 20:54:34,263] {logging_mixin.py:109} INFO - [2022-08-26 20:54:34,263] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:54:34,454] {logging_mixin.py:109} INFO - [2022-08-26 20:54:34,454] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 20:54:34,466] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:54:34,469] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.207 seconds
[2022-08-26 20:55:05,420] {processor.py:163} INFO - Started process (PID=17306) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:55:05,420] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-26 20:55:05,420] {logging_mixin.py:109} INFO - [2022-08-26 20:55:05,420] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:55:05,593] {logging_mixin.py:109} INFO - [2022-08-26 20:55:05,593] {dagbag.py:334} ERROR - Failed to import: /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/theonewiththelion/airflow/dags/Pushtobigquery2.py", line 4, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
[2022-08-26 20:55:05,605] {processor.py:656} WARNING - No viable dags retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-26 20:55:05,608] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.188 seconds
[2022-08-27 18:43:42,213] {processor.py:163} INFO - Started process (PID=22680) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:43:42,215] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-27 18:43:42,215] {logging_mixin.py:109} INFO - [2022-08-27 18:43:42,215] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:43:43,007] {logging_mixin.py:109} INFO - [2022-08-27 18:43:43,007] {utils.py:159} INFO - NumExpr defaulting to 8 threads.
[2022-08-27 18:43:43,277] {logging_mixin.py:109} INFO - Done
[2022-08-27 18:43:43,290] {processor.py:654} INFO - DAG(s) dict_keys(['ETL_Examples']) retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:43:43,300] {logging_mixin.py:109} INFO - [2022-08-27 18:43:43,300] {dag.py:2396} INFO - Sync 1 DAGs
[2022-08-27 18:43:43,305] {logging_mixin.py:109} INFO - [2022-08-27 18:43:43,305] {dag.py:2935} INFO - Setting next_dagrun for ETL_Examples to 2023-01-20T00:00:00+00:00
[2022-08-27 18:43:43,310] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 1.097 seconds
[2022-08-27 18:44:15,013] {processor.py:163} INFO - Started process (PID=22954) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:44:15,013] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-27 18:44:15,013] {logging_mixin.py:109} INFO - [2022-08-27 18:44:15,013] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:44:15,861] {logging_mixin.py:109} INFO - [2022-08-27 18:44:15,861] {utils.py:159} INFO - NumExpr defaulting to 8 threads.
[2022-08-27 18:44:16,121] {logging_mixin.py:109} INFO - Done
[2022-08-27 18:44:16,138] {processor.py:654} INFO - DAG(s) dict_keys(['ETL_Examples']) retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:44:16,149] {logging_mixin.py:109} INFO - [2022-08-27 18:44:16,149] {dag.py:2396} INFO - Sync 1 DAGs
[2022-08-27 18:44:16,154] {logging_mixin.py:109} INFO - [2022-08-27 18:44:16,154] {dag.py:2935} INFO - Setting next_dagrun for ETL_Examples to 2023-01-20T00:00:00+00:00
[2022-08-27 18:44:16,158] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 1.146 seconds
[2022-08-27 18:44:47,592] {processor.py:163} INFO - Started process (PID=23011) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:44:47,592] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-27 18:44:47,592] {logging_mixin.py:109} INFO - [2022-08-27 18:44:47,592] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:44:48,296] {logging_mixin.py:109} INFO - [2022-08-27 18:44:48,296] {utils.py:159} INFO - NumExpr defaulting to 8 threads.
[2022-08-27 18:44:48,481] {logging_mixin.py:109} INFO - Done
[2022-08-27 18:44:48,495] {processor.py:654} INFO - DAG(s) dict_keys(['ETL_Examples']) retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:44:48,505] {logging_mixin.py:109} INFO - [2022-08-27 18:44:48,505] {dag.py:2396} INFO - Sync 1 DAGs
[2022-08-27 18:44:48,509] {logging_mixin.py:109} INFO - [2022-08-27 18:44:48,509] {dag.py:2935} INFO - Setting next_dagrun for ETL_Examples to 2023-01-20T00:00:00+00:00
[2022-08-27 18:44:48,512] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.920 seconds
[2022-08-27 18:45:20,025] {processor.py:163} INFO - Started process (PID=23031) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:45:20,025] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-27 18:45:20,025] {logging_mixin.py:109} INFO - [2022-08-27 18:45:20,025] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:45:20,729] {logging_mixin.py:109} INFO - [2022-08-27 18:45:20,729] {utils.py:159} INFO - NumExpr defaulting to 8 threads.
[2022-08-27 18:45:20,925] {logging_mixin.py:109} INFO - Done
[2022-08-27 18:45:20,940] {processor.py:654} INFO - DAG(s) dict_keys(['ETL_Examples']) retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:45:20,950] {logging_mixin.py:109} INFO - [2022-08-27 18:45:20,950] {dag.py:2396} INFO - Sync 1 DAGs
[2022-08-27 18:45:20,954] {logging_mixin.py:109} INFO - [2022-08-27 18:45:20,954] {dag.py:2935} INFO - Setting next_dagrun for ETL_Examples to 2023-01-20T00:00:00+00:00
[2022-08-27 18:45:20,957] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.933 seconds
[2022-08-27 18:45:52,350] {processor.py:163} INFO - Started process (PID=23036) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:45:52,350] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-27 18:45:52,350] {logging_mixin.py:109} INFO - [2022-08-27 18:45:52,350] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:45:53,075] {logging_mixin.py:109} INFO - [2022-08-27 18:45:53,075] {utils.py:159} INFO - NumExpr defaulting to 8 threads.
[2022-08-27 18:45:53,256] {logging_mixin.py:109} INFO - Done
[2022-08-27 18:45:53,270] {processor.py:654} INFO - DAG(s) dict_keys(['ETL_Examples']) retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:45:53,280] {logging_mixin.py:109} INFO - [2022-08-27 18:45:53,279] {dag.py:2396} INFO - Sync 1 DAGs
[2022-08-27 18:45:53,284] {logging_mixin.py:109} INFO - [2022-08-27 18:45:53,284] {dag.py:2935} INFO - Setting next_dagrun for ETL_Examples to 2023-01-20T00:00:00+00:00
[2022-08-27 18:45:53,287] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.937 seconds
[2022-08-27 18:46:24,637] {processor.py:163} INFO - Started process (PID=23039) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:46:24,637] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-27 18:46:24,637] {logging_mixin.py:109} INFO - [2022-08-27 18:46:24,637] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:46:25,338] {logging_mixin.py:109} INFO - [2022-08-27 18:46:25,338] {utils.py:159} INFO - NumExpr defaulting to 8 threads.
[2022-08-27 18:46:25,524] {logging_mixin.py:109} INFO - Done
[2022-08-27 18:46:25,539] {processor.py:654} INFO - DAG(s) dict_keys(['ETL_Examples']) retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:46:25,549] {logging_mixin.py:109} INFO - [2022-08-27 18:46:25,549] {dag.py:2396} INFO - Sync 1 DAGs
[2022-08-27 18:46:25,554] {logging_mixin.py:109} INFO - [2022-08-27 18:46:25,554] {dag.py:2935} INFO - Setting next_dagrun for ETL_Examples to 2023-01-20T00:00:00+00:00
[2022-08-27 18:46:25,557] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.921 seconds
[2022-08-27 18:46:57,055] {processor.py:163} INFO - Started process (PID=23050) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:46:57,056] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-27 18:46:57,056] {logging_mixin.py:109} INFO - [2022-08-27 18:46:57,056] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:46:57,841] {logging_mixin.py:109} INFO - [2022-08-27 18:46:57,840] {utils.py:159} INFO - NumExpr defaulting to 8 threads.
[2022-08-27 18:46:58,077] {logging_mixin.py:109} INFO - Done
[2022-08-27 18:46:58,091] {processor.py:654} INFO - DAG(s) dict_keys(['ETL_Examples']) retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:46:58,100] {logging_mixin.py:109} INFO - [2022-08-27 18:46:58,100] {dag.py:2396} INFO - Sync 1 DAGs
[2022-08-27 18:46:58,105] {logging_mixin.py:109} INFO - [2022-08-27 18:46:58,104] {dag.py:2935} INFO - Setting next_dagrun for ETL_Examples to 2023-01-20T00:00:00+00:00
[2022-08-27 18:46:58,108] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 1.053 seconds
[2022-08-27 18:47:29,204] {processor.py:163} INFO - Started process (PID=23053) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:47:29,205] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-27 18:47:29,205] {logging_mixin.py:109} INFO - [2022-08-27 18:47:29,205] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:47:29,887] {logging_mixin.py:109} INFO - [2022-08-27 18:47:29,887] {utils.py:159} INFO - NumExpr defaulting to 8 threads.
[2022-08-27 18:47:30,039] {logging_mixin.py:109} INFO - Done
[2022-08-27 18:47:30,052] {processor.py:654} INFO - DAG(s) dict_keys(['ETL_Examples']) retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:47:30,062] {logging_mixin.py:109} INFO - [2022-08-27 18:47:30,061] {dag.py:2396} INFO - Sync 1 DAGs
[2022-08-27 18:47:30,066] {logging_mixin.py:109} INFO - [2022-08-27 18:47:30,066] {dag.py:2935} INFO - Setting next_dagrun for ETL_Examples to 2023-01-20T00:00:00+00:00
[2022-08-27 18:47:30,069] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.865 seconds
[2022-08-27 18:48:01,107] {processor.py:163} INFO - Started process (PID=23056) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:48:01,107] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-27 18:48:01,108] {logging_mixin.py:109} INFO - [2022-08-27 18:48:01,107] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:48:01,779] {logging_mixin.py:109} INFO - [2022-08-27 18:48:01,779] {utils.py:159} INFO - NumExpr defaulting to 8 threads.
[2022-08-27 18:48:01,924] {logging_mixin.py:109} INFO - Done
[2022-08-27 18:48:01,936] {processor.py:654} INFO - DAG(s) dict_keys(['ETL_Examples']) retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:48:01,945] {logging_mixin.py:109} INFO - [2022-08-27 18:48:01,945] {dag.py:2396} INFO - Sync 1 DAGs
[2022-08-27 18:48:01,949] {logging_mixin.py:109} INFO - [2022-08-27 18:48:01,949] {dag.py:2935} INFO - Setting next_dagrun for ETL_Examples to 2023-01-20T00:00:00+00:00
[2022-08-27 18:48:01,953] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.846 seconds
[2022-08-27 18:48:33,009] {processor.py:163} INFO - Started process (PID=23059) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:48:33,009] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-27 18:48:33,009] {logging_mixin.py:109} INFO - [2022-08-27 18:48:33,009] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:48:33,694] {logging_mixin.py:109} INFO - [2022-08-27 18:48:33,694] {utils.py:159} INFO - NumExpr defaulting to 8 threads.
[2022-08-27 18:48:33,856] {logging_mixin.py:109} INFO - Done
[2022-08-27 18:48:33,869] {processor.py:654} INFO - DAG(s) dict_keys(['ETL_Examples']) retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:48:33,879] {logging_mixin.py:109} INFO - [2022-08-27 18:48:33,879] {dag.py:2396} INFO - Sync 1 DAGs
[2022-08-27 18:48:33,883] {logging_mixin.py:109} INFO - [2022-08-27 18:48:33,883] {dag.py:2935} INFO - Setting next_dagrun for ETL_Examples to 2023-01-20T00:00:00+00:00
[2022-08-27 18:48:33,888] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.879 seconds
[2022-08-27 18:49:05,155] {processor.py:163} INFO - Started process (PID=23067) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:49:05,155] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-27 18:49:05,155] {logging_mixin.py:109} INFO - [2022-08-27 18:49:05,155] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:49:05,992] {logging_mixin.py:109} INFO - [2022-08-27 18:49:05,992] {utils.py:159} INFO - NumExpr defaulting to 8 threads.
[2022-08-27 18:49:06,264] {logging_mixin.py:109} INFO - Done
[2022-08-27 18:49:06,280] {processor.py:654} INFO - DAG(s) dict_keys(['ETL_Examples']) retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:49:06,291] {logging_mixin.py:109} INFO - [2022-08-27 18:49:06,291] {dag.py:2396} INFO - Sync 1 DAGs
[2022-08-27 18:49:06,296] {logging_mixin.py:109} INFO - [2022-08-27 18:49:06,296] {dag.py:2935} INFO - Setting next_dagrun for ETL_Examples to 2023-01-20T00:00:00+00:00
[2022-08-27 18:49:06,299] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 1.145 seconds
[2022-08-27 18:49:37,405] {processor.py:163} INFO - Started process (PID=23071) to work on /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:49:37,405] {processor.py:642} INFO - Processing file /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py for tasks to queue
[2022-08-27 18:49:37,405] {logging_mixin.py:109} INFO - [2022-08-27 18:49:37,405] {dagbag.py:500} INFO - Filling up the DagBag from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:49:38,098] {logging_mixin.py:109} INFO - [2022-08-27 18:49:38,097] {utils.py:159} INFO - NumExpr defaulting to 8 threads.
[2022-08-27 18:49:38,255] {logging_mixin.py:109} INFO - Done
[2022-08-27 18:49:38,268] {processor.py:654} INFO - DAG(s) dict_keys(['ETL_Examples']) retrieved from /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py
[2022-08-27 18:49:38,277] {logging_mixin.py:109} INFO - [2022-08-27 18:49:38,277] {dag.py:2396} INFO - Sync 1 DAGs
[2022-08-27 18:49:38,281] {logging_mixin.py:109} INFO - [2022-08-27 18:49:38,281] {dag.py:2935} INFO - Setting next_dagrun for ETL_Examples to 2023-01-20T00:00:00+00:00
[2022-08-27 18:49:38,284] {processor.py:171} INFO - Processing /Users/theonewiththelion/airflow/dags/Pushtobigquery2.py took 0.880 seconds
