[2022-09-03 14:02:49,486] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: etl_airflow.field_rename scheduled__2022-09-03T03:40:00+00:00 [queued]>
[2022-09-03 14:02:49,490] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: etl_airflow.field_rename scheduled__2022-09-03T03:40:00+00:00 [queued]>
[2022-09-03 14:02:49,490] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-03 14:02:49,490] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-09-03 14:02:49,490] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-03 14:02:49,494] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): field_rename> on 2022-09-03 03:40:00+00:00
[2022-09-03 14:02:49,503] {standard_task_runner.py:52} INFO - Started process 41291 to run task
[2022-09-03 14:02:49,513] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl_airflow', 'field_rename', 'scheduled__2022-09-03T03:40:00+00:00', '--job-id', '645', '--raw', '--subdir', 'DAGS_FOLDER/etl_airflowv2.py', '--cfg-path', '/var/folders/35/pzst1sv14yld_nkt23lk_vmr0000gn/T/tmpmxz74hpi', '--error-file', '/var/folders/35/pzst1sv14yld_nkt23lk_vmr0000gn/T/tmpomeb9k5j']
[2022-09-03 14:02:49,515] {standard_task_runner.py:77} INFO - Job 645: Subtask field_rename
[2022-09-03 14:02:49,541] {logging_mixin.py:109} INFO - Running <TaskInstance: etl_airflow.field_rename scheduled__2022-09-03T03:40:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2022-09-03 14:02:49,566] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=jonathan.dejesus.azor@gmail.com
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=etl_airflow
AIRFLOW_CTX_TASK_ID=field_rename
AIRFLOW_CTX_EXECUTION_DATE=2022-09-03T03:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-03T03:40:00+00:00
[2022-09-03 14:02:49,823] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 64] Host is down
[2022-09-03 14:02:49,823] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 64] Host is down
[2022-09-03 14:02:49,823] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
[2022-09-03 14:02:49,823] {_default.py:290} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2022-09-03 14:02:51,038] {logging_mixin.py:109} WARNING - Downloading:   0%|          | 0/200 [00:00<?, ?rows/s]
[2022-09-03 14:02:51,265] {logging_mixin.py:109} WARNING - Downloading: 100%|##########| 200/200 [00:00<00:00, 886.36rows/s]
[2022-09-03 14:02:51,265] {logging_mixin.py:109} WARNING - Downloading: 100%|##########| 200/200 [00:00<00:00, 883.92rows/s]
[2022-09-03 14:02:51,265] {logging_mixin.py:109} WARNING - 
[2022-09-03 14:02:51,273] {logging_mixin.py:109} INFO - Staging table extraction successfully completed
[2022-09-03 14:02:51,282] {logging_mixin.py:109} INFO -      incident_report_number  ... rep_time
0               20222381575  ...     2129
1               20222381479  ...     1935
2               20222381858  ...     2337
3               20222381688  ...     2201
4               20222381348  ...     1830
..                      ...  ...      ...
195             20222390765  ...     1208
196             20222391622  ...        7
197             20222391707  ...       27
198             20222391682  ...       37
199             20222391561  ...       10

[200 rows x 9 columns]
[2022-09-03 14:02:56,645] {logging_mixin.py:109} WARNING -   0%|          | 0/1 [00:00<?, ?it/s]
[2022-09-03 14:02:56,646] {gbq.py:604} INFO - 200 out of 200 rows loaded.
[2022-09-03 14:02:56,648] {logging_mixin.py:109} WARNING - 100%|##########| 1/1 [00:00<00:00, 993.91it/s]
[2022-09-03 14:02:56,649] {logging_mixin.py:109} WARNING - 
[2022-09-03 14:02:56,649] {logging_mixin.py:109} INFO - Staging 2 table completed successfully
[2022-09-03 14:02:56,650] {python.py:175} INFO - Done. Returned value was: None
[2022-09-03 14:02:56,667] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=etl_airflow, task_id=field_rename, execution_date=20220903T034000, start_date=20220903T190249, end_date=20220903T190256
[2022-09-03 14:02:56,694] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-09-03 14:02:56,705] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
