[2022-09-02 12:22:59,437] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: etl_crime.Extraction manual__2022-09-02T17:22:40.157847+00:00 [queued]>
[2022-09-02 12:22:59,440] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: etl_crime.Extraction manual__2022-09-02T17:22:40.157847+00:00 [queued]>
[2022-09-02 12:22:59,440] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-02 12:22:59,441] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-09-02 12:22:59,441] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-02 12:22:59,446] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): Extraction> on 2022-09-02 17:22:40.157847+00:00
[2022-09-02 12:22:59,454] {standard_task_runner.py:52} INFO - Started process 36599 to run task
[2022-09-02 12:22:59,458] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl_crime', 'Extraction', 'manual__2022-09-02T17:22:40.157847+00:00', '--job-id', '557', '--raw', '--subdir', 'DAGS_FOLDER/etl_bigquery.py', '--cfg-path', '/var/folders/35/pzst1sv14yld_nkt23lk_vmr0000gn/T/tmp7dqschy7', '--error-file', '/var/folders/35/pzst1sv14yld_nkt23lk_vmr0000gn/T/tmpgdnm7mlc']
[2022-09-02 12:22:59,478] {standard_task_runner.py:77} INFO - Job 557: Subtask Extraction
[2022-09-02 12:22:59,503] {logging_mixin.py:109} INFO - Running <TaskInstance: etl_crime.Extraction manual__2022-09-02T17:22:40.157847+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2022-09-02 12:22:59,528] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=jonathan.dejesus.azor@gmail.com
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=etl_crime
AIRFLOW_CTX_TASK_ID=Extraction
AIRFLOW_CTX_EXECUTION_DATE=2022-09-02T17:22:40.157847+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-02T17:22:40.157847+00:00
[2022-09-02 12:23:00,699] {logging_mixin.py:109} INFO -      incident_report_number  ... rep_time
0               20222391738  ...     2353
1               20222391646  ...     2346
2               20222391708  ...     2340
3               20222391707  ...       27
4               20222391682  ...       37
..                      ...  ...      ...
195             20222381037  ...     1626
196             20222381066  ...     1623
197             20222381057  ...     1601
198             20222380989  ...     1559
199             20222381059  ...     1630

[200 rows x 9 columns]
[2022-09-02 12:23:00,914] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 64] Host is down
[2022-09-02 12:23:00,914] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 64] Host is down
[2022-09-02 12:23:00,914] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
[2022-09-02 12:23:00,914] {_default.py:290} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2022-09-02 12:23:05,281] {logging_mixin.py:109} WARNING -   0%|          | 0/1 [00:00<?, ?it/s]
[2022-09-02 12:23:05,282] {gbq.py:604} INFO - 200 out of 200 rows loaded.
[2022-09-02 12:23:05,282] {logging_mixin.py:109} WARNING - 100%|##########| 1/1 [00:00<00:00, 3390.71it/s]
[2022-09-02 12:23:05,283] {logging_mixin.py:109} WARNING - 
[2022-09-02 12:23:05,283] {logging_mixin.py:109} INFO - Staging table completed successfully
[2022-09-02 12:23:05,283] {python.py:175} INFO - Done. Returned value was: None
[2022-09-02 12:23:05,290] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=etl_crime, task_id=Extraction, execution_date=20220902T172240, start_date=20220902T172259, end_date=20220902T172305
[2022-09-02 12:23:05,315] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-09-02 12:23:05,328] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
