[2022-09-03 14:01:21,828] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: etl_airflow.field_rename scheduled__2022-09-03T02:40:00+00:00 [queued]>
[2022-09-03 14:01:21,832] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: etl_airflow.field_rename scheduled__2022-09-03T02:40:00+00:00 [queued]>
[2022-09-03 14:01:21,832] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-03 14:01:21,832] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-09-03 14:01:21,832] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-03 14:01:21,836] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): field_rename> on 2022-09-03 02:40:00+00:00
[2022-09-03 14:01:21,843] {standard_task_runner.py:52} INFO - Started process 41226 to run task
[2022-09-03 14:01:21,847] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl_airflow', 'field_rename', 'scheduled__2022-09-03T02:40:00+00:00', '--job-id', '638', '--raw', '--subdir', 'DAGS_FOLDER/etl_airflowv2.py', '--cfg-path', '/var/folders/35/pzst1sv14yld_nkt23lk_vmr0000gn/T/tmpomry_73h', '--error-file', '/var/folders/35/pzst1sv14yld_nkt23lk_vmr0000gn/T/tmp4gnn3u0g']
[2022-09-03 14:01:21,848] {standard_task_runner.py:77} INFO - Job 638: Subtask field_rename
[2022-09-03 14:01:21,876] {logging_mixin.py:109} INFO - Running <TaskInstance: etl_airflow.field_rename scheduled__2022-09-03T02:40:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2022-09-03 14:01:21,899] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=jonathan.dejesus.azor@gmail.com
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=etl_airflow
AIRFLOW_CTX_TASK_ID=field_rename
AIRFLOW_CTX_EXECUTION_DATE=2022-09-03T02:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-03T02:40:00+00:00
[2022-09-03 14:01:22,140] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 64] Host is down
[2022-09-03 14:01:22,140] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 64] Host is down
[2022-09-03 14:01:22,141] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
[2022-09-03 14:01:22,141] {_default.py:290} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2022-09-03 14:01:23,345] {logging_mixin.py:109} WARNING - Downloading:   0%|          | 0/200 [00:00<?, ?rows/s]
[2022-09-03 14:01:23,575] {logging_mixin.py:109} WARNING - Downloading: 100%|##########| 200/200 [00:00<00:00, 880.54rows/s]
[2022-09-03 14:01:23,576] {logging_mixin.py:109} WARNING - Downloading: 100%|##########| 200/200 [00:00<00:00, 875.30rows/s]
[2022-09-03 14:01:23,576] {logging_mixin.py:109} WARNING - 
[2022-09-03 14:01:23,583] {logging_mixin.py:109} INFO - Staging table extraction successfully completed
[2022-09-03 14:01:23,593] {logging_mixin.py:109} INFO -      incident_report_number  ... rep_time
0               20222381575  ...     2129
1               20222381479  ...     1935
2               20222381858  ...     2337
3               20222381688  ...     2201
4               20222381348  ...     1830
..                      ...  ...      ...
195             20222390765  ...     1208
196             20222391622  ...        7
197             20222391707  ...       27
198             20222391682  ...       37
199             20222391561  ...       10

[200 rows x 9 columns]
[2022-09-03 14:01:29,624] {logging_mixin.py:109} WARNING -   0%|          | 0/1 [00:00<?, ?it/s]
[2022-09-03 14:01:29,627] {gbq.py:604} INFO - 200 out of 200 rows loaded.
[2022-09-03 14:01:29,629] {logging_mixin.py:109} WARNING - 100%|##########| 1/1 [00:00<00:00, 808.46it/s]
[2022-09-03 14:01:29,630] {logging_mixin.py:109} WARNING - 
[2022-09-03 14:01:29,631] {logging_mixin.py:109} INFO - Staging 2 table completed successfully
[2022-09-03 14:01:29,632] {python.py:175} INFO - Done. Returned value was: None
[2022-09-03 14:01:29,648] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=etl_airflow, task_id=field_rename, execution_date=20220903T024000, start_date=20220903T190121, end_date=20220903T190129
[2022-09-03 14:01:29,675] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-09-03 14:01:29,688] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
